/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vaaholundveeguueueuh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhYWhvbHVuZHZlZWd1dWV1ZXVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAwMzM0ODksImV4cCI6MjEwNTYwOTQ4OX0.kAc5LMXoeSpv_U-h-xQ5rsCD5xcOYZslGMN-zUTiTnQ"